### ISSUE TITLE
tools-oss-cad-suit build is broken?

### ISSUE THREAD

**Issue by zapta** [FPGAwars/tools-oss-cad-suite#10]
I am having difficulty to build the release files.  The build.sh file refer to tool-system version 1.1.2 but that version doesn't contains a release file for the aarch64 architecture.

https://github.com/FPGAwars/tools-oss-cad-suite/blob/fda165147260396391623f9186b2374377253871/build.sh#L43

https://github.com/FPGAwars/tools-system/releases

```
+ mkdir -p tools-system
+ cd tools-system
+ test -e tools-system-linux_aarch64-1.1.2.tar.gz
+ wget https://github.com/FPGAwars/tools-system/releases/download/v1.1.2/tools-system-linux_aarch64-1.1.2.tar.gz
--2024-10-18 12:42:38--  https://github.com/FPGAwars/tools-system/releases/download/v1.1.2/tools-system-linux_aarch64-1.1.2.tar.gz
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-10-18 12:42:38 ERROR 404: Not Found.
```

**Comment by cavearr** [comment]
Hi @zapta ! sorry the arm64 has no system tools package, i fix the error in the build script.

If works please close this issue.

Thanks!

**Comment by zapta** [comment]
Thanks @cavearr, it does build now. Closing.
