### ISSUE TITLE
oss-cad-suite gives a 404 error

### ISSUE THREAD

**Issue by FlyByPC** [FPGAwars/tools-oss-cad-suite#2]
I'm trying to install ICEStudio; automatic installation with the installer didn't go well, and it is reporting that oss-cad-suite isn't installed.

Running the script to install oss-cad-suite via apio, I get a 404 error:

(venv) C:\Users\Eric\.icestudio\venv\Scripts>apio install oss-cad-suite
(DEBUG) Profile path: C:\Users\Eric\.icestudio\apio\profile.json
(DEBUG) Home_dir: C:\Users\Eric\.icestudio\apio
Installing oss-cad-suite package:
Warning: full platform does not match: windows_x86
         Trying OS name: windows
Error: Got an unrecognized status code '404' when downloaded https://github.com/
FPGAwars/tools-oss-cad-suite/releases/download/v0.0.8/tools-oss-cad-suite-window
s-0.0.8.tar.gz

**Comment by aronfeher** [comment]
Same error inside WSL 

(.env) lindev@DESKTOP-BJUJSML:~/fpga_dev/tiny_bx_test/hdl$ apio install oss-cad-suite
(DEBUG) Profile path: /home/lindev/.apio/profile.json
(DEBUG) Home_dir: /home/lindev/.apio
File version.txt downloaded!
Version: 0.0.9
Installing oss-cad-suite package:
platform_download_url: https://github.com/FPGAwars/tools-oss-cad-suite/releases/download/v0.0.9/tools-oss-cad-suite-linux_x86_64-0.0.9.tar.gz
Warning: full platform does not match: linux_x86_64
         Trying OS name: linux
Error: Got an unrecognized status code '404' when downloaded https://github.com/FPGAwars/tools-oss-cad-suite/releases/download/v0.0.9/tools-oss-cad-suite-linux-0.0.9.tar.gz

**Comment by Obijuan** [comment]
@aronfeher could you please try it again? Currently we are upgrading the toolchains and version 0.0.9 has not already been released. I've reverted back to version 0.0.8 temporaly

**Comment by aronfeher** [comment]
@Obijuan Thank you for the quick reply. I've tested version 0.0.8, and it works on Windows and WSL perfectly.
