### ISSUE TITLE
Gowin

### ISSUE THREAD

**Issue by kimstik** [FPGAwars/tools-oss-cad-suite#3]
Any chance to add nextpnr-gowin ?

**Comment by zapta** [comment]
There is an ongoing apio work on adding Gowin. I am not sure how stable it is but it may be included in the next apio release.

**Comment by cavearr** [comment]
Maintain this open i want to paste integration results in short (probably today) and then close , ok?

**Comment by zapta** [comment]
Very good. Whenever it works for you.  Thanks.

**Comment by cavearr** [comment]
@zapta, all works! tried a simple RGB led example in :

- tang nano 1k 
- tang nano 9k
- tang nano 20k

I'm closing the issue, good work!
