### ISSUE TITLE
getting stuck at unpacking tools-oss-cad-suite-windows_amd64-0.0.8.tar.gz ,and uptime is too abnormal

### ISSUE THREAD

**Issue by Varad-97** [FPGAwars/tools-oss-cad-suite#6]
Installing oss-cad-suite package:
platform_download_url: https://github.com/FPGAwars/tools-oss-cad-suite/releases/download/v0.0.8/tools-oss-cad-suite-windows_amd64-0.0.8.tar.gz
Download tools-oss-cad-suite-windows_amd64-0.0.8.tar.gz
Downloading  [####################################]  100%          
Unpacking  [------------------------------------]    0%  20:25:19

**Comment by cavearr** [comment]
What is your username in windows? if username contain spaces could be the problem, if not , tell me and try to help you.

**Comment by Varad-97** [comment]
its simple just "LENOVO" in uppercase
spec :
Device name	DESKTOP-M9HOGAI
Processor	Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz   2.00 GHz
System type	64-bit operating system, x64-based processor

**Comment by cavearr** [comment]
ok, i have some tests and tell you

**Comment by Varad-97** [comment]
![Screenshot 2024-01-26 013843](https://github.com/FPGAwars/tools-oss-cad-suite/assets/139987161/6906cc27-9403-4b25-bf28-49b7a3624a9d)
it just happened,

**Comment by cavearr** [comment]
Could be problem of our github quota, sorry for the inconvenience.

**Comment by Obijuan** [comment]
The problem with  github was fixes some versions ago: the github api is no longer used by apio
