### ISSUE TITLE
apio min version decimal place error in package.json for apio version 0.10.0

### ISSUE THREAD

**Issue by ProbabilityEngineer** [FPGAwars/tools-oss-cad-suite#7]
I didn't know where to put this but -  to install the new 0.10.0 dev tools then 
package.json -

  "apio": {
    "min": "0.8.4",
    "max": "1.0.0", 

 must be changed to 

  "apio": {
    "min": "0.08.4",
    "max": "1.0.0",

as it is read as 0.80.4

The apio version is compared to .icestudo/venv/lib/python3.x/site-packages/apio-x/metadata which lists version 10 as 0.10.0. 

The .icestudio/packages/packages.json and  /tools-oss-cad-suite/package.json are not checked.

I really need to learn how to use github.

**Comment by ProbabilityEngineer** [comment]
[apio-min-version-package.json](https://github.com/FPGAwars/tools-oss-cad-suite/files/14080623/apio-min-version-package.json)

**Comment by cavearr** [comment]
Hi! I’m working on it could be unstable along the day . At the afternoon all works fine.

**Comment by cavearr** [comment]
hi! @ProbabilityEngineer thanks! for the moment the release numbers only go from 0 to 9, the error was my version 0.10.0 that conflicts with a pre-release that @Obijuan stablish previously, but for the future i'll change the logic to supports numbers like 0.10.0 and checks correctly agains 0.8.4 for example. For the moment i'm downgrading the number and publishing for development and wips the 0.9.1 apio version.

Thanks again!
