### ISSUE TITLE
Verilator doesn't work on Windows without Perl installed

### ISSUE THREAD

**Issue by JarrettR** [FPGAwars/tools-oss-cad-suite#9]
I have to confess, I haven't actually installed Perl to check the hypothesis that installing Perl will fix it.

But regardless:

```
PS D:\Projects\git\fp> apio upgrade
Local Apio version: 0.9.5
Lastest Apio stable version (Pypi): 0.9.5
You're up-to-date!
Apio 0.9.5 is currently the latest stable version available.
PS D:\Projects\git\fp> apio lint
verilator --lint-only --timing -Wno-TIMESCALEMOD channel.v pll.v serialInterface.v timescale.v top.v 
'verilator' is not recognized as an internal or external command,
operable program or batch file.
```

So Apio isn't able to pick up `verilator`

That makes sense, according to the install script:
https://github.com/FPGAwars/tools-oss-cad-suite/blob/main/scripts/install_windows_x64.sh#L156

Given that `verilator` is a [Perl script](https://github.com/verilator/verilator/blob/master/bin/verilator).
The purpose of the script appears to be to attach GDB to the executable, for debugging.

The fix, in my case was to go to `C:\Users\username\.apio\packages\tools-oss-cad-suite\bin`, remove `verilator`, and rename `verilator_bin.exe` to `verilator.exe`

But in this case, the install script getting changed would be more ideal.

**Comment by zapta** [comment]
Thanks for the report. The next release of apio will launch verilator_bin directly, on all platforms.

**Comment by zapta** [comment]
The fix was submitted. Closing.

**Comment by zapta** [comment]
@cavearr, the fix was submitted. We can close this one.

**Comment by cavearr** [comment]
Ok! closing it!
